blog/urls.py
from django.urls import path
from . import views

#Hier wird views.index geladen
app_name =  'blog'
urlpatterns = [
    path('',  views.index, name='index'),
]

web/urls.py
from django.urls import path
from . import views

#Hier wird views.index geladen
app_name =  'web'
urlpatterns = [
    path('',  views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('web.urls')),
]+ static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class ContactForm (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=250)
    email = models.EmailField(max_length=250, default=" ")
    created_at = models.DateTimeField(default=timezone.now)


class Comment (models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=250)
    created_at = models.DateTimeField(default=timezone.now)

web/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['message']

web/forms.py
from django import forms
from django.contrib.auth.models import User

class RegisterForm(forms.Form):
    username = forms.CharField(max_length=35, label='Username eintragen')
    email = forms.EmailField(label='Email eintragen')
    password = forms.CharField(min_length=6, max_length=50, label='Passwort eintragen', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError("Diesen Username gibt es schon")
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError('Diese Email gibt es schon')
        return email

class LoginForm(forms.Form):
    username = forms.CharField(max_length=35, label='Username eintragen')
    password = forms.CharField(min_length=6, max_length=50, label="Passwort eintragen", widget=forms.PasswordInput)

blog/views.py
import json
from django.shortcuts import render
import xml.etree.ElementTree as ET
from django.contrib.auth.decorators import login_required
from .models import ContactForm, Comment
from .forms import CommentForm as cf
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

@csrf_exempt
@login_required
def index (request): 

    # XML-Datei parsen
    tree = ET.parse('xml/data.xml')
    root = tree.getroot()


    # Daten extrahieren
    blog_daten = []
    for auto in root:
        auto_daten = {}
        auto_daten['marke'] = auto.find('Automarke').text
        auto_daten['bezeichnung'] = auto.find('Autobezeichnung').text
        technische_details = auto.find('Technische_Details')
        auto_daten['leistung'] = technische_details.find('Leistung').text
        auto_daten['drehmoment'] = technische_details.find('max_Drehmomemt').text
        auto_daten['hubraum'] = technische_details.find('Hubraum').text
        auto_daten['zylinderzahl'] = technische_details.find('Zylinderzahl').text
        auto_daten['verbrauch'] = technische_details.find('Verbrauch').text
        auto_daten['getriebe'] = technische_details.find('Getriebe').text
        auto_daten['leergewicht'] = technische_details.find('Leergewicht').text
        auto_daten['hoechstgeschwindigkeit'] = technische_details.find('Hoechstgeschwindigkeit').text
        auto_daten['beschleunigung_0_100'] = technische_details.find('Beschleunigung_0_100').text
        auto_daten['erscheinungsjahr'] = technische_details.find('Erscheinungsjahr').text
        auto_daten['anzahl_tueren'] = technische_details.find('Anzahl_tueren').text
        auto_daten['farbe'] = technische_details.find('Farbe').text  # neues Attribut
        auto_daten['preis'] = technische_details.find('Preis').text    # neues Attribut
        auto_daten['baujahr'] = technische_details.find('Baujahr').text  # neues Attribut
        auto_daten['image_url'] = technische_details.find('image_url').text
        auto_daten['beschreibung'] = technische_details.find('beschreibung').text

        blog_daten.append(auto_daten)

    #Get the Intupt from Frotend contact Form
    if request.method == 'POST' and  request.content_type == 'application/json':  
        
        # JSON-Daten aus der Anfrage lesen
        daten = json.loads(request.body)
        email1 = daten.get('email')
        text = daten.get('text')


        contact_form = ContactForm(

            user =  request.user,
            email = email1,
            message =text
        )

        contact_form.save()


    comment_form = cf()
    if request.method == 'POST' and  'submit_comment' in request.POST and not request.content_type == 'application/json':
        comment_form = cf(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.save()


    comments = Comment.objects.all()


    return render(request, 'blog/index.html',  {'blog_daten': blog_daten, 'comments': comments, 'comment_form': comment_form})

web/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.urls.base import reverse
from .forms import RegisterForm, LoginForm
from django.contrib.auth.models import User


# Create your views here.

def index(request):
    if request.user.is_authenticated:
       return redirect(reverse('blog:index'))
    return render(request, 'web/base.html')


def register_view (request):

    if request.user.is_authenticated:
       return redirect(reverse('blog:index'))

    register_form = RegisterForm()

    if request.method == "POST":
     register_form = RegisterForm(request.POST)
     if register_form.is_valid():
        email = register_form.cleaned_data['email']
        username = register_form.cleaned_data['username']
        password = register_form.cleaned_data['password']
        User.objects.create_user(username=username,password=password,email=email)
        user = authenticate(request, username=username, password=password) 
        if user:
            login(request, user)
            return redirect(reverse('web:index'))


    return render (request, 'web/register.html', {'register_form': register_form})

def login_view (request):
    if request.user.is_authenticated:
       return redirect(reverse('blog:index'))

    login_form = LoginForm

    if request.method == 'POST':
        login_form =  LoginForm(data=request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
               login(request, user)
               return redirect(reverse('blog:index'))


    return render (request, 'web/login.html',  {'login_form': login_form})


def logout_view (request):

    logout(request)
    return redirect(reverse('web:index'))

web/templates/login/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    {% load static  %} <!-- Load static files -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/Autblog.css' %}"> <!-- External CSS -->

    <title>{% block title %}  Standard {% endblock %}</title>
</head>
<body>
    
    {% block authForm %}

    {% endblock %}
</body>
</html>

web/templates/login/login.html
{% extends 'web/base.html' %}

{% block title %}  Login {% endblock %}

{% block authForm %}

 <form method="post" action="">

    {{login_form.as_p }}
    <button type="submit">Login</button>

 </form>

{% endblock %}

web/templates/login/register.html
{% extends 'web/base.html' %}

{% block title %}  Account anlegen {% endblock %}

{% block authForm %}

 <form method="post" action="">

    {{ register_form.as_p }}

    <button type="submit">Account anlegen</button>


 </form>

{% endblock %}

web/templates/web/base.html
<!DOCTYPE html>
<html lang="de">
<head>
    {% load static  %} <!-- Load static files -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/Autblog.css' %}"> <!-- External CSS -->

    <title>{% block title %}  Standard {% endblock %}</title>
</head>
<body>
    {% if request.user.is_authenticated %}

    <a href="{% url 'web:logout' %}">Logout</a><li></li>

   <p>Hi </p> 
    
    {% else %}

    <a href="{% url 'web:login' %}">Login</a><li></li>
    <a href="{% url 'web:register' %}">Account anlegen</a><li></li>

    {% endif %}



    
    {% block authForm %}

    {% endblock %}
</body>
</html>

web/templates/web/login.html
{% extends 'web/base.html' %}

{% block title %}  Login {% endblock %}

{% block authForm %}

 <form method="post" action="">
   {% csrf_token %}

    {{login_form.as_p }}
    <button type="submit">Login</button>

 </form>

{% endblock %}

web/templates/web/register.html
{% extends 'web/base.html' %}

{% block title %}  Account anlegen {% endblock %}

{% block authForm %}

 <form method="post" action="">
   {% csrf_token %}

    {{ register_form.as_p }}

    <button type="submit">Account anlegen</button>


 </form>

{% endblock %}